### ISSUE TITLE
Instructions for the hip-hop video

### ISSUE THREAD

**Issue by RaymondBalise** [juliasilge/juliasilge.com#80]
Hi Julia,
I just tried to leave clues for people who want to replicate your results on this post:
https://juliasilge.com/blog/best-hip-hop/

I *love* that post but it was a bit of a pain because {spotifyr} is not on CRAN and the GitHub repo would not build.

You will see I left a partial post ... (sigh).  I was trying to move the cursor to a new line and instead it saved a partial post.  Can you kill it?  Also It looks like I used four backticks instead of three to start a code block and I can't edit it.  (sigh again) If you can easily tweak it can you kill the extra backtick so the instructions look clean. 

Note to self: Don't post before 6 am...

**Comment by juliasilge** [comment]
I think it looks OK, both on GitHub and the blog itself! You are able to delete it if you want, but looks fine to me. 👍

**Comment by RaymondBalise** [comment]
I figured out that I could tweak it on GitHub early this morning.  I thought I had closed the issue after I fixed it.  Sorry for the noise.

Ray

Raymond R. Balise, PhD
Associate  Professor
Department of Public Health Sciences, Biostatistics

University of Miami, Miller School of Medicine
1120 N.W. 14th Street
Don Soffer Clinical Research Center - Room 1061
Miami, Florida 33136

(305) 243-9694

To request help from the Center for HIV and Research in Mental Health (CHARM) please go here<https://redcap.miami.edu/surveys/?s=EEWDYECME7>.  To provide post-consult feedback go here<https://redcap.miami.edu/surveys/?s=EYMEPRMCJP&consultant=1>. Please remember to acknowledge CHARM in your papers if resources were used (P30MH116867).

Confidentiality Notice: This e-mail transmission, and any documents, files or previous e-mail messages attached to it, may contain confidential information. If you are not the intended recipient, or a person responsible for delivering it to the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of any of the information contained in or attached to this message is STRICTLY PROHIBITED. If you have received this transmission in error, please immediately notify us by reply e-mail or by telephone at (305) 243-9694  and destroy the original transmission and its attachments without reading them or saving them to disk.



From: Julia Silge ***@***.***>
Date: Wednesday, December 14, 2022 at 11:43 AM
To: juliasilge/juliasilge.com ***@***.***>
Cc: Balise, Raymond R ***@***.***>, State change ***@***.***>
Subject: [EXTERNAL] Re: [juliasilge/juliasilge.com] Instructions for the hip-hop video (Issue #80)
CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.


I think it looks OK, both on GitHub and the blog itself! You are able to delete it if you want, but looks fine to me. 👍
